apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment  
spec:  
  selector:
    matchLabels:
      app: myapp
  replicas: 2      
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: yankogp/test
        ports:
        - containerPort: 80